# Generated by Django 4.2.7 on 2023-12-08 06:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date(2023, 12, 8))),
                ('start', models.TimeField(default=django.utils.timezone.now)),
                ('end', models.TimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('workers', models.ManyToManyField(related_name='meets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
