# Generated by Django 4.2.7 on 2023-12-09 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='room',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 9)),
        ),
    ]
