# Generated by Django 4.2.7 on 2023-12-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0004_alter_meet_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
