# Generated by Django 4.2.7 on 2023-12-15 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0007_alter_meet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 15)),
        ),
    ]
