# Generated by Django 5.0 on 2023-12-16 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meets', '0008_alter_meet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 16)),
        ),
    ]
