# Generated by Django 4.2.7 on 2023-12-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_prescription_test_patient_description_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Mężczyzna'), ('female', 'Kobieta')], default='male', max_length=20),
        ),
    ]
