# Generated by Django 4.2.7 on 2023-12-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='terrain',
            field=models.CharField(choices=[('zachodnio-pomorskie', 'Zachodnio-Pomorskie'), ('pomorskie', 'Pomorskie'), ('warminsko-pomorskie', 'Warmińsko-Pomorskie'), ('podlaskie', 'Podlaskie'), ('lubelskie', 'Lubelskie'), ('mazowieckie', 'Mazowieckie'), ('kujawsko-pomorskie', 'Kujawsko-Pomorskie'), ('wielkopolskie', 'Wielkopolskie'), ('lubuskie', 'Lubuskie'), ('dolnoslaskie', 'Dolnośląskie'), ('slaskie', 'Śląskie'), ('opolskie', 'Opolskie'), ('lodzkie', 'Łódzkie'), ('swietokrzyskie', 'Świętokrzyskie'), ('malopolskie', 'Małopolskie'), ('podkarpackie', 'Podkarpackie')], default='lubelskie', max_length=40),
        ),
    ]
