# Generated by Django 4.2.7 on 2023-12-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
