# Generated by Django 4.2.7 on 2023-12-07 07:36

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='date_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meet',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='worker',
            name='birthday',
            field=models.DateField(default=datetime.date(2023, 12, 7)),
        ),
    ]
