# Generated by Django 4.2.7 on 2023-12-08 06:14

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_meet_date_end_meet_date_start_worker_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='date_start',
        ),
        migrations.AddField(
            model_name='meet',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 8)),
        ),
        migrations.AddField(
            model_name='meet',
            name='end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meet',
            name='start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(default=datetime.date(2023, 12, 8)),
        ),
    ]
