# Generated by Django 4.2.7 on 2023-12-09 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_delete_meet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(default=datetime.date(2023, 12, 9)),
        ),
    ]
