# Generated by Django 4.2.7 on 2023-12-10 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_alter_worker_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(default=datetime.date(2023, 12, 10)),
        ),
    ]
