# Generated by Django 4.2.7 on 2023-12-11 05:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_alter_worker_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(default=datetime.date(2023, 12, 11)),
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('change', models.CharField(max_length=10)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
