# Generated by Django 4.2.7 on 2023-12-15 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_alter_worker_birthday_workhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhours',
            name='change_hours',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(default=datetime.date(2023, 12, 15)),
        ),
    ]
