# Generated by Django 4.2.7 on 2023-12-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_workhours_change_hours_alter_worker_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workhours',
            name='change_hours',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
