# Generated by Django 5.0 on 2023-12-16 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0009_alter_workhours_change_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workhours',
            name='change',
        ),
        migrations.RemoveField(
            model_name='workhours',
            name='change_hours',
        ),
        migrations.AddField(
            model_name='workhours',
            name='end',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='workhours',
            name='start',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name='worker',
            name='birthday',
            field=models.DateField(default=datetime.date(2023, 12, 16)),
        ),
    ]
